version: '3.3'

services:
  traefik:
    image: traefik:v1.7
    ports:
      - 80:80
    deploy:
      replicas: ${TRAEFIK_REPLICAS:-1}
      placement:
        constraints:
          - node.role == manager
        preferences:
          - spread: node.id
      labels:
        - traefik.frontend.rule=Host:${TRAEFIK_FQDN:-traefik.localhost}
        - traefik.enable=true
        - traefik.port=8080
        - traefik.tags=proxy
        - traefik.docker.network=proxy
        - traefik.redirectorservice.frontend.entryPoints=http
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: >
      --docker
      --docker.swarmmode
      --docker.watch
      --docker.exposedbydefault=false
      --constraints=tag==proxy
      --entrypoints='Name:http Address::80'
      --logLevel=INFO
      --accessLog
      --api
    networks:
      - proxy

networks:
  proxy:
    external: true
